name: Publish Release

on:
  push:
    branches:
      - release
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get current date
        id: date
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Update version in Cargo.toml
        run: |
          sed -i "s/^version = .*/version = \"0.1.${{ steps.date.outputs.date }}\"/" Cargo.toml
          git add Cargo.toml
          git commit -m "chore: bump version to 0.1.${{ steps.date.outputs.date }}"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Commit Cargo.lock changes
        run: |
          git add Cargo.lock
          git commit -m "chore: update Cargo.lock" || echo "No changes to commit"

      - name: Push release branch
        run: git push origin release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release 0.1.${{ steps.date.outputs.date }}
          tag_name: v0.1.${{ steps.date.outputs.date }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

      - name: Rebase main branch onto release
        run: |
          git fetch origin main
          git checkout main
          git rebase release
          git push origin main